language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- pytest
before_install:
- openssl aes-256-cbc -K $encrypted_1e032544a30b_key -iv $encrypted_1e032544a30b_iv
  -in id_rsa.enc -out ../../.ssh/id_rsa -d
