language: python
python:
- '3.5'
sudo: required
addons:
  chrome: stable
install:
- sudo apt-get update
- sudo apt-get install chromium-chromedriver
- sh -e /etc/init.d/xvfb start
- pip install -r requirements.txt
script:
- pytest
