language: python
python:
- '3.5'
sudo: required
addons:
  chrome: stable
install:
- pip install -r requirements.txt
before_script:
- wget http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python35/bin/
- export CHROME_BIN=chromium-browser
script:
- pytest
