language: python
python:
- '3.5'
before_install:
- wget http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d
/home/travis/virtualenv/python2.7.12/bin/
- export CHROME_BIN=chromium-browser

install:
- pip install -r requirements.txt
script:
- pytest
